version: '3'

services:
  db:
    image: mysql:5.6
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=mmndb
    volumes: 
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  wordpress:
    depends_on: 
      - db
    image: wordpress:6.2.2-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=mmndb
    volumes:
      - wordpress:/var/www/html
      - ./wp-content/themes/rebalance:/var/www/html/wp-content/themes/rebalance 
      - ./wp-content/themes/rebalance-child-mmn:/var/www/html/wp-content/themes/rebalance-child-mmn 
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
      - ./fonts:/var/www/html/fonts
      - ./moneymakestheworldgoround:/var/www/html/moneymakestheworldgoround
      - ./manifesto:/var/www/html/manifesto
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.16.1-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - ./wp-content/themes/rebalance:/var/www/html/wp-content/themes/rebalance 
      - ./wp-content/themes/rebalance-child-mmn:/var/www/html/wp-content/themes/rebalance-child-mmn 
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
      - ./fonts:/var/www/html/fonts
      - ./moneymakestheworldgoround:/var/www/html/moneymakestheworldgoround
      - ./manifesto:/var/www/html/manifesto
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - app-network

  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - wordpress:/var/www/html
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  certbot-etc:
  wordpress:
  dbdata:

networks:
  app-network:
    driver: bridge 
